name: Playwright Tests
on:
  push:
    branches: [ main, master, log_in ]
  pull_request:
    branches: [ main, master, log_in ]
jobs:
  test:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    #- name: Install cross-env
    #  run: npm install --save-dev cross-env
    #- name: Install Cucumber
    #  run: npm install --save-dev @cucumber/cucumber

    # Install Multiple Cucumber HTML Reporter
    - name: Install reporter
      run: npm install multiple-cucumber-html-reporter --save-dev
    
      # Install the allure command line and also install the Allure reporter
    # - name: Install the allure command line
    #  run: npm install -g allure-commandline --save-dev
    #- name: install the Allure reporter
    #  run: npm i -D @playwright/test allure-playwright
      # Run Playwright tests and creating the Allure report
    #- name: Run Playwright tests
    #  run: |
    #    npx playwright test --reporter=line,allure-playwright

    - name: Run Cucumber tests
      # run: npx cucumber-js test || true
      run: npm test
    # - name: Run allure-results and allure-report
    #  run: |
    #    allure generate allure-results -o allure-report --clean
    #    allure open allure-report 
    
    
    # Run Multiple Cucumber HTML Reporter
    #- name: Run reporter
    #  run: npx ts-node src/helper/report.ts 
    - name: Output the run Details  
      uses: actions/upload-pages-artifact@v1
      # if: always()
      with:
    #    name: Test results
        #path: test-results
        #retention-days: 30
        path: '.'

  # Upload the contents of Test Results directory to workspace
  #- name: Output the run Details
  #uses: actions/upload-pages-artifact@v1
  #with:
    # Upload entire repository
  #  path: '.'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
        id-token: write 
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
